modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
# issueTrackerURL = "https://github.com/2653003971-bot/HoldYourCamera/issues"   #

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    authors = "${mod_authors}"
    displayTest = "IGNORE_ALL_VERSION"    # 纯客户端 mod：服务器没装也不在列表里标红叉
    description = '''${mod_description}'''

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "CLIENT"
